global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'webapp'
    static_configs:
      - targets: ['webapp:5000']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
